version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - "./qdrant_storage:/qdrant/storage:z"


  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    image: docs-rag:1.0
    volumes:
      - hf_data:/app/hf_cache
      - qdrant_data:/app/qdrant_storage
    ports:
      - 8501:8501
    depends_on:
      - qdrant
    command: bash -c "entrypoint.sh"

volumes:
  hf_data:
  qdrant_data: